name: assignment_4_cst407
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  jikan_api: ^1.3.1
  flutter_riverpod: ^0.5.1
  flutter_pagewise: ^1.2.3
  google_nav_bar: ^2.2.0
  line_icons: ^0.2.0 #icon for bottom navigation bar
  google_sign_in: ^4.5.1 #google-signin
  like_button: ^1.0.1 #like-button on detail screen
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  flutter_login: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
